name: 'Security Scanning'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # schedule:
  #   - cron: '0 8 * * 1' # Run once a week on Monday

jobs:
  security-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.11.0']

    steps:
      - uses: actions/checkout@v4

      # Improved PNPM setup
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.2
          run_install: false # Important: don't run install yet

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # Remove the cache line that's causing the issue
          # cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # pnpm audit - Check for package vulnerabilities
      - name: Run pnpm audit
        run: pnpm audit --audit-level=high

      # ESLint security plugins check - use pnpm instead of npx
      - name: Run ESLint
        run: pnpm eslint . --ext .js,.jsx,.ts,.tsx

      # Dependency scanning
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To not fail the build
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      # Secrets scanning
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.46.3
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      # Update to v3 as v2 is deprecated
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
