name: 'Security Scanning'
run-name: 'Security Scan for ${{ github.event_name }}'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Node.js with Corepack enabled
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      # Enable Corepack to manage package managers
      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@10.6.2 --activate

      # Cache with version control
      # - name: Cache pnpm dependencies
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.pnpm-store
      #       node_modules
      #     # Adding a cache version (v2) to start fresh
      #     key: ${{ runner.os }}-pnpm-cache-v2-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pnpm-cache-v2-

      # Install dependencies with fresh setup
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # pnpm audit - Check for package vulnerabilities
      - name: Run pnpm audit
        run: pnpm audit --audit-level=high

      # ESLint security plugins check
      - name: Run ESLint
        run: pnpm eslint . --ext .js,.jsx,.ts,.tsx

      # Dependency scanning
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      # Secrets scanning
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.46.3
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
